// AUTO-GENERATED by scripts/gen-content-index.mjs — do not edit by hand.
// Static imports (not fs reads, not template-literal dynamic imports) so Next
// bundles every content JSON without output-file-tracing surprises on the
// standalone prod build.
import type { SiteTexts } from "@/app/_landing/types";
import type { BlogArticleContent } from "@/app/_landing/blog/types";
import type { EditorTexts } from "@/app/_editor/texts";
import chrome_en from "./chrome/en.json";
import editor_en from "./editor/en.json";
import blog_en_exportMermaidToPngSvg from "./blog/export-mermaid-to-png-svg/en.json";
import blog_en_mermaidSequenceDiagram from "./blog/mermaid-sequence-diagram/en.json";
import blog_en_mermaidSyntaxCheatSheet from "./blog/mermaid-syntax-cheat-sheet/en.json";

// Marketing copy + UI chrome, per locale.
export const CHROME: Record<string, SiteTexts> = {
  "en": chrome_en as unknown as SiteTexts,
};

// Editor workspace strings, per locale.
export const EDITOR: Record<string, EditorTexts> = {
  "en": editor_en as unknown as EditorTexts,
};

// Blog articles keyed by `${locale}/${articleId}`.
export const BLOG_CONTENT: Record<string, BlogArticleContent> = {
  "en/export-mermaid-to-png-svg": blog_en_exportMermaidToPngSvg as unknown as BlogArticleContent,
  "en/mermaid-sequence-diagram": blog_en_mermaidSequenceDiagram as unknown as BlogArticleContent,
  "en/mermaid-syntax-cheat-sheet": blog_en_mermaidSyntaxCheatSheet as unknown as BlogArticleContent,
};

// Locales whose chrome AND editor strings both exist — the rollout gate for
// static params, sitemap, hreflang and the footer's language switcher. A
// locale with only half its files would render a half-English page.
export const READY_LOCALES: string[] = ["en"];
