import MANIFEST_JSON from "@/content/blog/manifest.json";
import { BLOG_CONTENT } from "@/content";
import type { BlogArticleContent, BlogManifestEntry } from "./types";

// Newest first — the index page and "related articles" both read this order.
export const BLOG_ARTICLES: BlogManifestEntry[] = (MANIFEST_JSON as BlogManifestEntry[])
  .slice()
  .sort((a, b) => (a.date < b.date ? 1 : -1));

export function blogEntry(id: string): BlogManifestEntry | undefined {
  return BLOG_ARTICLES.find((a) => a.id === id);
}

/** Article content for a locale, falling back to English when a translation
 *  has not shipped yet. Static imports (content/index.ts, generated by
 *  scripts/gen-content-index.mjs) rather than a dynamic `import()`: the prod
 *  build is a standalone one, and file-tracing a template-literal import is
 *  exactly where that goes wrong. */
export function blogArticle(id: string, locale: string): BlogArticleContent | null {
  return BLOG_CONTENT[`${locale}/${id}`] ?? BLOG_CONTENT[`en/${id}`] ?? null;
}

export type BlogCardData = {
  entry: BlogManifestEntry;
  title: string;
  excerpt: string;
};

function toCard(entry: BlogManifestEntry, locale: string): BlogCardData | null {
  const content = blogArticle(entry.id, locale);
  return content ? { entry, title: content.card.title, excerpt: content.card.excerpt } : null;
}

/** Every article's card copy for a locale, newest first (blog index). */
export function blogIndexCards(locale: string): BlogCardData[] {
  return BLOG_ARTICLES.map((e) => toCard(e, locale)).filter((c): c is BlogCardData => c !== null);
}

/** The N newest other articles (the "related" band on an article page). */
export function blogRelated(locale: string, excludeId: string, n = 2): BlogCardData[] {
  return BLOG_ARTICLES.filter((e) => e.id !== excludeId)
    .slice(0, n)
    .map((e) => toCard(e, locale))
    .filter((c): c is BlogCardData => c !== null);
}

/** Localized long-form date for cards and the article header. */
export function formatBlogDate(iso: string, locale: string): string {
  return new Intl.DateTimeFormat(locale, { year: "numeric", month: "long", day: "numeric" }).format(
    new Date(`${iso}T00:00:00Z`),
  );
}
